---
title: "🎄🎄🎄 day 24  🎄🎄🎄"
output: github_document
---
```{r , include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(here)
```


### Part 1

```{r}
# hexagonal compass lookup table
r3 <- sqrt(3)
lkup <- tribble(~compass, ~x, ~y,
               "w", -1, 0,
               "e", +1, 0,
               "nw", -1/2, r3/2,
               "ne", +1/2, r3/2,
               "sw", -1/2, -r3/2,
               "se", +1/2, -r3/2
               ) %>% 
  mutate(num = 1:n())

# fn to transalte and collapse flips

collapse_flips <- function(flips){
  tibble(compass = flips[[1]]) %>% 
    left_join(lkup, by = "compass") %>% 
    summarise(x = sum(x), y = sum(y))
}
```

```{r}

# do flips

tiles <- read_lines(here("day_24","test.txt")) %>%
  as_tibble() %>% 
  mutate(instruction = 1:n()) %>% 
  mutate(compass = map(value, str_extract_all, "(w|e|nw|ne|sw|se)")) %>% 
  mutate(collapse = map(compass, collapse_flips)) %>% 
  unnest(collapse) %>% 
  select(-compass) %>% 
  group_by(x, y) %>% 
  tally() %>% 
  ungroup()



tiles %>% 
  count(n)

ggplot(tiles) +
  aes(x, y, fill = factor(n)) +
  geom_hex(stat = "identity", colour = "grey90") +
  scale_fill_manual(values = c("black", "red")) +
  theme_void() +
  theme(legend.position = "none") +
  coord_equal() +
  labs(captions = "red tiles:- flipped twice")
```

### Part 2

1. Any black tile with zero or more than 2 black tiles immediately adjacent to it is flipped to white.
2. Any white tile with exactly 2 black tiles immediately adjacent to it is flipped to black.

```{r}
# just record black tiles
tiles <- tiles %>% 
  filter(n == 1)


count_neighbours <- function(x, y){
  tibble(x, y) %>% 
    crossing(lkup %>% rename(dx = x, dy = y)) %>% 
    mutate(nx = x + dx,
           ny = y + dy) %>% 
    left_join(tiles, by = c("nx" = "x", "ny" = "y")) %>% 
    summarise(total = sum(n, na.rm = TRUE)) %>% 
    pull(total)
}


for(ii in 1:100){
  print(ii)
  flush.console()
  tiles %>% 
  mutate(neighbours = map2_int(x, y, count_neighbours)) %>%
  mutate(n = case_when(n == 1 & neighbours == 0 ~ 2,
                       n == 1 & neighbours >  2 ~ 2,
                       n == 2 & neighbours == 2 ~ 1))
}

  
```


